site_name: OpenCentauri
repo_url: https://github.com/suchmememanyskill/OpenCentauri
repo_name: OpenCentauri
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - git-committers:
      repository: suchmememanyskill/OpenCentauri
      branch: main
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enable_creation_date: true
nav:
  - Home: index.md
  - Machine:
    - Machine: machine/index.md
    - Mainboard: machine/mainboard.md
    - Hotend: machine/hotend.md
    - Bed: machine/bed.md
    - Screen: machine/screen.md
  - Software: 
    - Software: software/index.md
    - Partitions: software/partitions.md
    - Updates: software/updates.md
    - API: software/api.md
  - Klipper via mainboard replacement:
    - Main: klipper-via-mainboard-replacement/index.md
    - Recognize Hotend: klipper-via-mainboard-replacement/recognize-hotend.md
    - Full Config: klipper-via-mainboard-replacement/full-config.md
  - Mods:
    - Printable Mods: mods/printable_mods.md
    - Light Mods: mods/light_mods.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expand
    - toc.integrate
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/t6Cft3wNJ3